# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "server"

[target.server]
type = "executable"
sources = ["src/**.cpp", "inc/**.hpp", "src/**.c", "inc/**.h"]
include-directories = ["inc"]
compile-features = ["cxx_std_20"]